### ISSUE TITLE
Regular expressions Metacharacters validation for the content blocker

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/SafariContentBlockerConverterCompiler#1]
The issue is described here:
https://github.com/AdguardTeam/AdguardForiOS/issues/128#issuecomment-238498979

We should find a better way to validate regular expression.

**Comment by Mizzick** [comment]
Ok

**Comment by ameshkov** [comment]
@Mizzick just in case, here is a class used by them to compile "url-filter" regular expressions (named `PatternParser`):
https://github.com/WebKit/webkit/blob/master/Source/WebCore/contentextensions/URLFilterParser.cpp#L41

Basically this is a delegate class which implements methods like `atomCharacterClassAtom` or `atomBuiltInCharacterClass` and such (which are called in process of regexp parsing). In some methods it fails specifically and that's why regexp syntax is limited for content blockers.

For instance, look at how it's done for meta characters.
1. When parser stumbles upon a meta character, [it calls `atomBuiltInCharacterClass` method](https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/yarr/YarrParser.h#L298).
2. However, in the content blocking URLFilterParser this delegate method [instantly fails](https://github.com/WebKit/webkit/blob/master/Source/WebCore/contentextensions/URLFilterParser.cpp#L201).
